apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: mi-prueba
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: harbor.itsos.ar/library/hello-world-web:latest
        name: helloworld
        ports:
        - containerPort: 8080
