apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: mi-prueba
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: adejonge/helloworld:latest
        name: helloworld
        ports:
        - containerPort: 8080
