apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roldyx-prueba
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/roldyxoriginal/devops-toolkit.git
    targetRevision: HEAD
    path: argocd/mi-prueba
  destination:
    server: https://kubernetes.default.svc
    namespace: default
